-- Availability was generated by PostgreSQL in its session timezone; all other
-- timestamps were supplied by the application as UTC instants.
ALTER TABLE "RoadmapNotice"
  ALTER COLUMN "availableAt" TYPE TIMESTAMPTZ(3) USING "availableAt" AT TIME ZONE current_setting('TimeZone'),
  ALTER COLUMN "occurredAt" TYPE TIMESTAMPTZ(3) USING "occurredAt" AT TIME ZONE 'UTC',
  ALTER COLUMN "seenAt" TYPE TIMESTAMPTZ(3) USING "seenAt" AT TIME ZONE 'UTC',
  ALTER COLUMN "acknowledgedAt" TYPE TIMESTAMPTZ(3) USING "acknowledgedAt" AT TIME ZONE 'UTC';
ALTER TABLE "NoticeAcknowledgement"
  ALTER COLUMN "openedAt" TYPE TIMESTAMPTZ(3) USING "openedAt" AT TIME ZONE 'UTC';
